// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsBaIBNvTgjR88nySBez5HI0j-9IIYfo',
    appId: '1:579050440192:web:a7225578a1b5f1fca37ae5',
    messagingSenderId: '579050440192',
    projectId: 'travel-map-app-9e670',
    authDomain: 'travel-map-app-9e670.firebaseapp.com',
    storageBucket: 'travel-map-app-9e670.firebasestorage.app',
    measurementId: 'G-13NSBZNW53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9tzM5k5uu6GUWxIxr6QrkmXhjZoi8kk',
    appId: '1:579050440192:android:6690ec4b06c84938a37ae5',
    messagingSenderId: '579050440192',
    projectId: 'travel-map-app-9e670',
    storageBucket: 'travel-map-app-9e670.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VyTuwmgrmPvkdlV7Wm1f8xkl-Vcl_mI',
    appId: '1:579050440192:ios:ff61a2e6e645ace6a37ae5',
    messagingSenderId: '579050440192',
    projectId: 'travel-map-app-9e670',
    storageBucket: 'travel-map-app-9e670.firebasestorage.app',
    iosBundleId: 'com.example.travelMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VyTuwmgrmPvkdlV7Wm1f8xkl-Vcl_mI',
    appId: '1:579050440192:ios:ff61a2e6e645ace6a37ae5',
    messagingSenderId: '579050440192',
    projectId: 'travel-map-app-9e670',
    storageBucket: 'travel-map-app-9e670.firebasestorage.app',
    iosBundleId: 'com.example.travelMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsBaIBNvTgjR88nySBez5HI0j-9IIYfo',
    appId: '1:579050440192:web:bec1dba720706f7da37ae5',
    messagingSenderId: '579050440192',
    projectId: 'travel-map-app-9e670',
    authDomain: 'travel-map-app-9e670.firebaseapp.com',
    storageBucket: 'travel-map-app-9e670.firebasestorage.app',
    measurementId: 'G-53Q1NNHQFQ',
  );
}
